apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: ES_ADDRESS
              value: http://elasticsearch:9200
            - name: ES_PASSWORD
              value: thisisaverystrongpassword
            - name: ES_USERNAME
              value: elastic
            - name: KC_CLIENT_ID
              value: msg-poc-backend
            - name: KC_ISSUER
              value: http://keycloak:7080/realms/msg-poc
          image: backend
          name: poc-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
