apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: VITE_API_URL
              value: http://localhost:4000
            - name: VITE_AUTH_URL
              value: http://localhost:8080/realms/msg-poc/protocol/openid-connect
            - name: VITE_CLIENT_ID
              value: msg-poc-front
          image: frontend
          name: poc-frontend
          ports:
            - containerPort: 4040
              protocol: TCP
      restartPolicy: Always
