apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: init-elasticsearch
  name: init-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: init-elasticsearch
    spec:
      containers:
        - command:
            - /bin/sh
            - /init.sh
          image: appropriate/curl
          name: init-elasticsearch
          volumeMounts:
            - mountPath: /init.sh
              name: init-elasticsearch-cm0
              subPath: init.sh
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sh
                path: init.sh
            name: init-elasticsearch-cm0
          name: init-elasticsearch-cm0
