services:
  mailhog:
    build:
      context: ./mailhog
    ports:
      - ${MH_UI_BIND_ADDR_PORT}:${MH_UI_BIND_ADDR_PORT}
    env_file:
      - ./.env 

  react:
    build:
      context: ./react
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env 
    volumes:
      - ./react/src:/app/src:rw
